/**
 * Test stand-in for the `virtual:pwa-register/react` module.
 *
 * WHY:  The real module is generated by vite-plugin-pwa during a build and
 *       talks to a service worker, which jsdom does not have.
 * HOW:  Exposes the same `useRegisterSW` shape. Tests replace it per case with
 *       `vi.mock("virtual:pwa-register/react", ...)`; this default reports
 *       "no update waiting".
 * WHEN: Wired in through `test.alias` in vite.config.ts.
 */
export function useRegisterSW(): {
  needRefresh: [boolean, (value: boolean) => void];
  offlineReady: [boolean, (value: boolean) => void];
  updateServiceWorker: (reloadPage?: boolean) => Promise<void>;
} {
  return {
    needRefresh: [false, () => undefined],
    offlineReady: [false, () => undefined],
    updateServiceWorker: () => Promise.resolve(),
  };
}
